/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DistributionRouteImport } from './routes/distribution'
import { Route as SubstationRouteImport } from './routes/substation'
import { Route as TransformerRouteImport } from './routes/transformer'
import { Route as TransmissionRouteImport } from './routes/transmission'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionRoute = DistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const SubstationRoute = SubstationRouteImport.update({
  id: '/substation',
  path: '/substation',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformerRoute = TransformerRouteImport.update({
  id: '/transformer',
  path: '/transformer',
  getParentRoute: () => rootRouteImport,
} as any)
const TransmissionRoute = TransmissionRouteImport.update({
  id: '/transmission',
  path: '/transmission',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/distribution': typeof DistributionRoute
  '/substation': typeof SubstationRoute
  '/transformer': typeof TransformerRoute
  '/transmission': typeof TransmissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/distribution': typeof DistributionRoute
  '/substation': typeof SubstationRoute
  '/transformer': typeof TransformerRoute
  '/transmission': typeof TransmissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/distribution': typeof DistributionRoute
  '/substation': typeof SubstationRoute
  '/transformer': typeof TransformerRoute
  '/transmission': typeof TransmissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/distribution' | '/substation' | '/transformer' | '/transmission'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/distribution' | '/substation' | '/transformer' | '/transmission'
  id:
    | '__root__'
    | '/'
    | '/distribution'
    | '/substation'
    | '/transformer'
    | '/transmission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistributionRoute: typeof DistributionRoute
  SubstationRoute: typeof SubstationRoute
  TransformerRoute: typeof TransformerRoute
  TransmissionRoute: typeof TransmissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution': {
      id: '/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/substation': {
      id: '/substation'
      path: '/substation'
      fullPath: '/substation'
      preLoaderRoute: typeof SubstationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformer': {
      id: '/transformer'
      path: '/transformer'
      fullPath: '/transformer'
      preLoaderRoute: typeof TransformerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transmission': {
      id: '/transmission'
      path: '/transmission'
      fullPath: '/transmission'
      preLoaderRoute: typeof TransmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistributionRoute: DistributionRoute,
  SubstationRoute: SubstationRoute,
  TransformerRoute: TransformerRoute,
  TransmissionRoute: TransmissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
